In [1]:
import pandas as pd
import warnings
import numpy as np
warnings.simplefilter(action='ignore', category=FutureWarning)
import os

In [2]:
df_unit=pd.read_csv("d:\\solar-performance-monitoring\\data\\interim\\unit_data.csv")
df_error=pd.read_csv("d:\\solar-performance-monitoring\\data\\interim\\error_data.csv")

In [14]:
df_unit.head()

        date  E-Today(KWH)
0 2024-11-16             8
1 2024-11-17            40
2 2024-11-18            39
3 2024-11-19            39
4 2024-11-20            36

In [ ]:

df_unit['date'] = pd.to_datetime(df_unit['date'], errors='coerce')
df_unit.drop_duplicates(inplace=True)

<class 'pandas.DataFrame'>
Index: 507 entries, 0 to 507
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          507 non-null    datetime64[us]
 1   E-Today(KWH)  507 non-null    int64
dtypes: datetime64[us](1), int64(1)
memory usage: 11.9 KB

In [3]:
df_error.head()

             time/date                    event        date
0  2024-11-19 17:35:06    A1-Grid under voltage  2024-11-19
1  2024-11-19 17:35:06           A2-Grid absent  2024-11-19
2  2024-11-19 17:35:06  A4-Grid under frequency  2024-11-19
3  2024-11-19 17:35:06    A1-Grid under voltage  2024-11-19
4  2024-11-19 17:35:06           A2-Grid absent  2024-11-19

In [4]:
df_error.info()

<class 'pandas.DataFrame'>
RangeIndex: 2016 entries, 0 to 2015
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   time/date  2016 non-null   str
 1   event      2016 non-null   str
 2   date       2016 non-null   str
dtypes: str(3)
memory usage: 47.4 KB

In [6]:
df_error['time/date'] = pd.to_datetime(df_error['time/date'], errors='coerce')
df_error['date'] = df_error['time/date'].dt.date
df_error['date'] = pd.to_datetime(df_error['date'])
df_error.drop_duplicates(inplace=True)

In [8]:
df_error.head()

            time/date                    event       date
0 2024-11-19 17:35:06    A1-Grid under voltage 2024-11-19
1 2024-11-19 17:35:06           A2-Grid absent 2024-11-19
2 2024-11-19 17:35:06  A4-Grid under frequency 2024-11-19
6 2024-11-23 11:18:09    A1-Grid under voltage 2024-11-23
7 2024-11-23 11:18:09  A4-Grid under frequency 2024-11-23

In [7]:
df_error.info()

<class 'pandas.DataFrame'>
Index: 1969 entries, 0 to 2015
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   time/date  1969 non-null   datetime64[us]
 1   event      1969 non-null   str
 2   date       1969 non-null   datetime64[s]
dtypes: datetime64[s](1), datetime64[us](1), str(1)
memory usage: 61.5 KB